---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qijun.
--- DateTime: 2020/1/31 20:24
---
local function compare1(x,y)
    return x > y
end

local a = {1,2,3,4,5,8,10,11.2}

print(1.22 > 1)

table.sort(a,compare1)

print(a)

local table1 = {1,2, xy="3"}


for i, v in pairs(table1) do
    print(string.format("i= %s v= %s",i,v))
end

for i, v in ipairs(a) do
    print("i=",i,"v=",v)
end


if a ~= nil then
    print(a[1])
end

--数组

--闭包

function test()
    local i = 0
    return function()
        i = i + 1;
        return i;
    end
end
local c1 = test();
print(c1())
print(c1())

mytable = setmetatable({key1 = "value"},
        {__index =
         function (self,key)
            if key == "key2" then
             return "metatablevalue"
            end
         end})
print(mytable.key1,mytable.key2)